import "./globals.css";
import { ThemeContextProvider } from "./theme/ThemeContextProvider";

export const metadata = {
  title: "Pantry Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeContextProvider>{children}</ThemeContextProvider>
      </body>
    </html>
  );
}
